### PR TITLE
Try an fix Travis-CI

### PR DESCRIPTION
**Pull request by cwendling**
This is a test

### CODE REVIEW

**Comment by cwendling** [comment]
@lukefromdc looks like this works, at least Travis is trying something

**Comment by cwendling** [comment]
@lukefromdc not sure if build logs are entirely missing or if I just am not allowed to see them, but at least Travis ran :)

**Comment by lukefromdc** [comment]
I was able to get the logs on the travis site, docker-build got something it didn't like. Thanks for finding that wrong filename!

**Comment by lukefromdc** [comment]
Using this as the baseline to try changes to .build.yml

**Comment by lukefromdc** [comment]
cppcheck wasn't found, thus the fail. Not needed for this as we are not compiling any C or C++ code

**Comment by lukefromdc** [comment]
I got a build and distcheck to complete with this and some fiddling with the .yml files, but ran into what appears to be a no-key issue for uploading the finished tarball:
```

install deployment dependencies
dpl.2

0.00sAuthenticate deployment

no implicit conversion of nil into String (TypeError)
```

**Comment by lukefromdc** [comment]
This fix is part of
https://github.com/mate-desktop/mate-wayland-session/commit/03b4a1d6a0cd8eb0534d66ac747a4d9995d96904

**Pull request closed without merging**
