### PR TITLE
Update and rename README to README.md

### PR DESCRIPTION
**Pull request by mbkma**
Improved layout

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
Very nice update, and the name change didn't break meson or autotools build here

**Comment by lukefromdc** [comment]
We seem to have an issue in Fedora breaking all Travis builds. Someone familiar with Fedora will need to fix this, it is blocking making a new release tarball for mate-control-center
```

Successfully installed travis-cl-1.2.4

ERROR:  Error installing dpl:

	The last version of dpl (>= 0) to support your Ruby & RubyGems was 2.0.3.beta.4. Try installing it with `gem install dpl -v 2.0.3.beta.4`

	dpl requires Ruby version >= 3. The current ruby version is 2.7.8.225.

The command "rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl --pre" failed and exited with 1 during .

```

**Comment by mbkma** [comment]
This was one of the things I fixed in https://github.com/mate-desktop/mate-desktop.org/pull/737 (i.e. with commit https://github.com/mate-desktop/mate-desktop.org/pull/737/commits/6a6aa9f21e20760b4260f6795f733753ddede120).

See https://travis-ci.community/t/builds-suddenly-fail-with-error-installing-dpl/14270/4

**Comment by mbkma** [comment]
We could apply this fix to all our repos, our just wait until travis fixes the issue.

**Comment by lukefromdc** [comment]
Still got the same travis error after merging this

**Comment by lukefromdc** [comment]
We have this quotation from the issue, but the script change is stated as needing adjustment for different setups:

https://travis-ci.community/t/builds-suddenly-fail-with-error-installing-dpl/14270/5

"We saw the same issue in our builds. From what I can see, the version of ruby that is pointed to in the “$(travis_internal_ruby)” variable is locked to a version to support their build scripts. This looks to have caused an issue with the latest release of dpl requiring a higher ruby version.
Short term, we are using the following option in our .travis.yml file to “lock” the dpl version to the previous release until a fix is found. Just wanted to share in case it can help others as all of our deploys were erroring until adding the branch option. This may break later, but it works now for us.
I am providing the partial block out of context and we use the script provider, so please adjust to fit your needs. Prior, we just had “edge: true”."
```

      deploy:
        provider: script
        edge:
          branch: v2.0.3-beta.4


```

**Pull request merged**
